dist: trusty
sudo: required
git:
  depth: false
install:
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine
script: |
  source .travis/common.sh
  alpine_run $USER .travis/build-pkgs
notifications:
  email: false
